import { StyleSheet, Dimensions, StatusBar } from "react-native";
import { colors } from "../styles/colors";
// Detect screen width and height
const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  containerApp: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: colors.GRAYS_WHITE,
    flexDirection: "column",
  },
  headerContainer: {
    flex: 0.1,
    height: 55,
    width: "100%",
    top: 0,
    paddingHorizontal: 10,
    flexDirection: "row",
    elevation: 0.3,
    alignItems: "center",
    position: "absolute",
    backgroundColor: colors.BASE_TEXT_COLOR,
  },
  header_txtStyle: {
    color: "white",
    textAlign: "center",
    alignSelf: "center",
    marginLeft: "2%",
    fontSize: 18,
  },
  headerLogo: {
    width: 43,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    borderWidth: 1,
  },
  input: {
    paddingHorizontal: 14,
    overflow: "hidden",
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: "#EDEEF1",
    marginHorizontal: "5%",
    height: 40,
  },
  inputBox: {
    borderColor: "black",
    backgroundColor: "red",
    borderWidth: 1,
    borderRadius: 23,
    overflow: "hidden",
  },
  //login Screen
  loginText: {
    color: "black",
    fontWeight: "500",
    fontSize: 20,
    marginStart: "6%",
    marginTop: "5%",
    textAlign: "left",
  },
  loginButton: {
    backgroundColor: "#242F65",
    color: "red",
    height: 40,
    marginHorizontal: "5%",
    borderRadius: 10,
    marginTop: "5%",
    alignItems: "center",
    justifyContent: "center",
  },
  login_txt: {
    color: "#ffffff",
    fontWeight: "500",
  },
  continueText: {
    color: "grey",
    fontSize: 14,
    marginStart: "6%",
    textAlign: "left",
    //marginVertical: "2%",
    marginBottom: "2%",
  },
  forgotPassText: {
    color: "#242F65",
    fontWeight: "500",
    textAlign: "right",
    marginEnd: "5%",
  },
  card: {
    width: "100%",
    height: "70%",
    alignSelf: "center",
    backgroundColor: "white",
    position: "absolute",
    bottom: 0,
    elevation: 5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  CreteNewButton: {
    color: "red",
    height: 40,
    marginHorizontal: "5%",
    borderRadius: 10,
    marginTop: "5%",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.5,
    borderColor: "#EDEEF1",
  },
  Createnew_txt: {
    color: "#242F65",
    fontWeight: "500",
  },
  card: {
    width: "100%",
    height: "70%",
    alignSelf: "center",
    backgroundColor: "white",
    position: "absolute",
    bottom: 0,
    elevation: 5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  LogRegText: {
    fontSize: 20,
    color: "#000",
    fontWeight: "500",
    marginTop: "25%",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  backbtnView: {
    width: 40,
    height: 40,
    position: "absolute",
    top: 20,
    left: 20,
    backgroundColor: "white",
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  backicon: {
    height: "50%",
    width: "50%",
  },
  forgorPassText: {
    fontSize: 20,
    color: "#000",
    marginHorizontal: "7%",
    fontWeight: "500",
  },
  forgotPassSubText: {
    fontSize: 15,
    marginHorizontal: "7%",
    marginVertical: 10,
  },
  logo_style: { height: 180, width: 180, marginTop: 10 },
  TopText: {
    fontSize: 18,
    color: "#000",
    fontWeight: "500",
    textAlign: "left",
  },
  textpara: {
    fontSize: 13,
    marginTop: 10,
    textAlign: "center",
  },
  bottomView: {
    backgroundColor: "#3B2A96",
    position: "absolute",
    bottom: 0,
    height: 60,
    width: "100%",
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    alignContent: "flex-end",
  },
  BottomTxt: {
    color: "#000",
    fontWeight: "500",
    textAlign: "center",
    fontSize: 13,
    textAlign: "center",
  },
  loginEyeCrossiconStyle: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignSelf: "center",
  },
  errorTextStyle: {
    color: "#3B2A96",
    textAlign: "center",
    fontSize: 14,
  },
  text_input: {
    flex: 1,
    marginTop: -12,
    paddingLeft: 10,
  },
  action: {
    flexDirection: "row",
    marginTop: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#3B2A96",
    //paddingBottom: 5,
  },
  loginEyeCrossiconStyle: {
    flexDirection: "row",
    right: 40,
    top: 30,
  },
  backbtn: {
    width: 40,
    height: 40,
    position: "absolute",
    top: 20,
    left: 20,
    backgroundColor: "white",
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  backicon: {
    height: "50%",
    width: "50%",
  },

  card1: {
    width: "100%",
    height: "70%",
    alignSelf: "center",
    backgroundColor: "white",
    position: "absolute",
    bottom: 0,
    elevation: 5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  card2: {
    width: "100%",
    height: "60%",
    alignSelf: "center",
    backgroundColor: "white",
    position: "absolute",
    bottom: 0,
    elevation: 5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  eyebutton_style: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignContent: "center",
    alignSelf: "center",
  },
  eye_icon_style: { position: "absolute", right: 12, bottom: 10 },
  eye_icon: {
    height: 15,
    width: 18,
    tintColor: "grey",
  },
  //detailed Screen style
  image_background_color: {
    backgroundColor: "#F0F1F2",
    flex: 2,
  },
  inputBox: {
    borderColor: "black",
    backgroundColor: "red",
    borderWidth: 1,
    borderRadius: 23,
    overflow: "hidden",
  },
  content: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: colors.WHITE,
    marginTop: 5,
    padding: 10,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  headerContainerDashboard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "red",
    marginTop: StatusBar.currentHeight,
    paddingTop: 24,
    paddingBottom: 20,
  },
  seeAll: {
    width: 20,
    height: 20,
    backgroundColor: colors.GRAYS_WHITE,
    borderColor: colors.GRAYS_WHITE,
    borderWidth: 1,
    borderRadius: 40,
    marginRight: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  seeAllicon: {
    width: 18,
    height: 18,
  },
  categoryStyle: {
    width: 65,
    height: 65,
    backgroundColor: colors.BLACK_TWO,
    borderColor: colors.BLACK_TWO,
    borderWidth: 1,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center'
  },
  brandStyle: {
    width: 59,
    height: 59,
    backgroundColor: colors.GRAYS_WHITE,
    borderColor: colors.GRAYS_WHITE,
    borderWidth: 1,
    borderRadius: 50,
    // marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center'
  },
  brandContainer: {
    width: 60,
    height: 60,
    borderRadius: 50,
    borderRadius: 8,
    marginRight: 16,
    marginLeft: 10,
    marginVertical: 15,
    justifyContent: 'center',
    alignItems: 'center'
  },
  listContainer: {
    flexDirection: 'column',
  },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  itemImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 16,
  },
  itemName: {
    fontSize: 18,
    flex: 1,
  },
  removeButton: {
    color: 'red',
  },
  image: {
    width: "100%",
    height: 150,
    resizeMode: "cover", // or 'contain' based on your preference
    borderRadius: 8,
    marginBottom: 8,
    overflow: "hidden",
    position: "relative", // or 'absolute' based on your layout
  },
  wish_container: {
    flex: 1,
    margin: 10,
    backgroundColor: colors.GRAYS_WHITE,
    borderRadius: 8,
    padding: 8,

  },
  remove: {
    width: 28,
    height: 28,
    backgroundColor: colors.GRAYS_WHITE,
    right: "5%",
    marginTop: 5,
    position: "absolute",
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  profileText: {
    fontSize: 11,
    color: colors.BASE_TEXT_COLOR,
    fontWeight: '400',
  },
  commonTouchProfile: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    alignItems: 'center',
    marginHorizontal: 10,
  },
  lineView: {
    width: '100%',
    height: 0.5,
    backgroundColor: colors.GRAYS_WHITE
  },

  iconStyle: {
    height: 18, width: 18, resizeMode: 'contain'
  },
  filerStyle: {
    flexDirection: 'row',
    padding: 4,
    backgroundColor: colors.WHITE,
    borderRadius: 5
  },
  filterText: {
    fontSize: 12,
    color: colors.BLACK,
    fontWeight: '700'
  },
  textStyle: {
    fontSize: 11,
    paddingHorizontal: 5,
    color: colors.BLACK
  },
  filterIconStyle: {
    height: 12,
    width: 16,
    alignSelf: 'center',
    paddingHorizontal: 2,
    resizeMode: 'contain'
  },

  //   justifyContent: "center",
  //   alignItems: "center",
  // },
  containerCategory: {
    marginVertical: 10,
  },
  listContainer: {
    flexDirection: "column",
  },
  itemContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  itemImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 16,
  },
  itemName: {
    fontSize: 18,
    flex: 1,
  },
  removeButton: {
    color: "red",
  },
  image: {
    width: 150,
    height: 150,
    resizeMode: "cover", // or 'contain' based on your preference
    borderRadius: 8,
    marginBottom: 8,
    overflow: "hidden",
    position: "relative", // or 'absolute' based on your layout
  },
  wish_container: {
    flex: 1,
    margin: 10,
    backgroundColor: colors.GRAYS_WHITE,
    borderRadius: 8,
    padding: 8,
  },
  remove: {
    width: 28,
    height: 28,
    backgroundColor: colors.GRAYS_WHITE,
    right: "5%",
    marginTop: 5,
    position: "absolute",
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  // home screen's styles
  slideImageView: { paddingBottom: 5, height: 200 },
  catView: { flexDirection: "row", justifyContent: 'flex-end' },
  seeAllText: {
    fontSize: 12,
    color: colors.DARK_BLACK,
    marginRight: 5,
    alignSelf: "center",
  },
  scrollStyle: { flexDirection: 'column', marginTop: '1%' },
  brandViewStyle: { marginTop: '3%' },
  branssubViewStyle: {
    justifyContent: "space-between",
    flexDirection: "row",
    marginVertical: "1%",
  },
  brandTextStyle: {
    fontSize: 17,
    color: colors.DARK_BLACK,
    fontWeight: "500"
  },

  seeAllTouch: { padding: 5, flexDirection: "row" },
  flashSaleView: { justifyContent: "space-between", flexDirection: "row", marginTop: '3%' },
  jacketMainView: { backgroundColor: '#DACCC4', width: '100%', height: 150, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  jacketImageStyle: { width: 120, height: 120 },
  jacketTextView: { alignItems: 'center', marginHorizontal: 10, justifyContent: 'center' },
  jacketMainText: { textTransform: 'capitalize', fontWeight: 'bold', color: '#000', fontSize: 18, },
  jacketSubText: { fontSize: 10, color: '#000', marginVertical: 5 },
  viewAllView: {
    borderRadius: 2,
    backgroundColor: colors.BLACK,
    justifyContent: "center",
    alignItems: "center",
    width: 60, height: 25,
    alignContent: 'center', marginTop: 10
  },
  viewAllText: {
    textTransform: "uppercase",
    color: "#fff",
    fontWeight: "500",
    fontSize: 10,
    textAlign: 'center'
  },
  jacketTextStyle: { textTransform: "uppercase", fontWeight: 'bold', color: '#000', fontSize: 17, maxWidth: '100%', marginVertical: 10 },
  tshirtImageStyle: { height: 120, width: '100%' },
  tshirtMainText: { textTransform: 'capitalize', fontWeight: 'bold', color: '#fff', fontSize: 18, maxWidth: '95%', marginTop: '10%', marginHorizontal: 10 },
  tshirtSubText: { fontSize: 10, color: '#fff', marginHorizontal: 15 },
  tshirtViewAllStyle: {
    borderRadius: 2,
    backgroundColor: '#fff',
    justifyContent: "center",
    alignItems: "center",
    width: 60, height: 25,
    alignContent: 'center', marginTop: 5,
    marginHorizontal: 15
  },
  tshirtViewAllText: {
    textTransform: "uppercase",
    color: "#000",
    fontWeight: "500",
    fontSize: 10,
    textAlign: 'center'
  },
  feetMainView: { justifyContent: 'center', alignItems: 'center', flex: 1 },
  feetViewAllButton: {
    borderRadius: 2,
    borderColor: colors.BLACK,
    justifyContent: "center",
    alignItems: "center",
    width: 60, height: 25,
    alignContent: 'center', marginTop: 10,
    borderWidth: 0.5
  },
  feetImagestyle: { width: 150, height: 150 },
  beautyMainView: { backgroundColor: '#E2D3D4', width: '100%', height: 150, flexDirection: 'row', alignSelf: 'center' },
  beautyImageStyle: { width: 150, height: 150 },
  beautySubView: { justifyContent: 'center', marginHorizontal: 20 },

  beautyMainText: { textTransform: 'capitalize', fontWeight: 'bold', color: '#000', fontSize: 18, },
  beautySubText: { fontSize: 10, color: '#000', marginVertical: 5, maxWidth: '80%' },
  BagMainView: { backgroundColor: '#DACCC4', width: '100%', height: 150, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', },
  BagImageStyle: { width: 120, height: 120 },
  bagSubView: { justifyContent: 'center', },
  bagMainText: { textTransform: 'capitalize', fontWeight: 'bold', color: '#000', fontSize: 18, maxWidth: '70%' },
  earingMainView: { backgroundColor: '#244F32', width: '100%', height: 150, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', },
  earingTextView: { textTransform: 'capitalize', fontWeight: 'bold', color: '#fff', fontSize: 18, },
  earingSubTextView: { fontSize: 10, color: '#fff' },
  earingSellView: {
    borderRadius: 2,
    justifyContent: "center",
    alignItems: "center",
    width: 60, height: 25,
    alignContent: 'center', marginTop: 10,
    borderColor: '#fff',
    borderWidth: 0.5
  },
  earingImageView: { width: 130, height: 130 },
  salesImageStyle: { height: 120, width: '100%' },
  salesMainText: {
    textTransform: 'capitalize',
    fontWeight: 'bold', color: '#fff',
    fontSize: 18,
    maxWidth: '95%',
    marginTop: '8%',
    marginHorizontal: 10,
    textAlign: 'center'
  },
  salesSubText: { fontSize: 10, color: '#fff', textAlign: 'center', marginVertical: 5 },
  salesViewAllView: {
    borderRadius: 2,
    backgroundColor: '#fff',
    justifyContent: "center",
    alignItems: "center",
    width: 60, height: 25,
    alignContent: 'center',
    marginHorizontal: 15,
    alignItems: 'center', alignSelf: 'center'
  },
  salesViewAll: {
    textTransform: "uppercase",
    color: "#000",
    fontWeight: "500",
    fontSize: 10,
    textAlign: 'center'
  },
  salesMainText: {
    textTransform: 'capitalize',
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 18, maxWidth: '95%',
    marginTop: '8%',
    marginHorizontal: 10
  },
  salesSubText: { fontSize: 10, color: '#fff', marginHorizontal: 10, marginVertical: 5 },
  salesViewAllView: {
    borderRadius: 2,
    backgroundColor: '#fff',
    justifyContent: "center",
    alignItems: "center",
    width: 60,
    height: 25,
    alignContent: 'center',
    marginHorizontal: 10

  },
  salesViewAllText: {
    textTransform: "uppercase",
    color: "#000",
    fontWeight: "500",
    fontSize: 10,
    textAlign: 'center'
  },
// favorite screen '
renderTouchView:{
  backgroundColor: colors.GRAYS_WHITE,
  marginVertical: 10,
  padding: 10,
  borderRadius: 8,
  flex: 1,
  margin: 10,
},
likeicon:{ height: 15, width: 15, tintColor: "#FF7F7F" },
priceView:{
  flexDirection: "row",
  justifyContent: "space-between",
  marginVertical: 4,
},
offerText:{ color: "#FF7F7F" },
ratingView:{
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "flex-end",
},
ratingText:{ color: "#000" },
ratingIcon:{
  height: 14,
  width: 14,
  resizeMode: "contain",
  left: 4,
  tintColor: "#03A685",
},reviewText:{
  marginStart: 5,
  color: "grey",
},
});

export default styles;
