export default {
  app_name_txt: "KaufliApp",
  login_txt: "Login",
  logout_user: "Logout",
  sure_want_logout: "are you sure you want to logout?",
  signup_new: "New here ? Register",
  already_login: "Already have an account? SignIn",
  signup_txt: "SignUp",
  enter_email: "Enter Email Address",
  enter_name: "Enter Name",
  enter_password: "Enter Password",
  enter_mobile: "Enter Mobile Number",
  enter_confirmpassword: "Enter Confirm Password",
  enter_address: "Enter Address",
  signup_emp: "Your account registered successfully",
  invalid_manager_id: "Invalid Id !!!!",
  invalid_email: "That email address is invalid!",
  already_in_use_email: "That email address is already in use!",
  enter_mobile_num: "Enter mobile number",
  forget_password_main_text: "Forgot Password?",
  forgot_button_text: "Forget Password",
  forget_password_sub_text:
    "Don’t worry you can re-create your password by using your email . Please enter your email to continue the process—",

  have_account_text: "We have an acount?",
  dont_have_acc_text: "Don't have an acount?",
  sign_in_text: " Sign In",
  create_new_text: " Create new",
};
